vrrp_instance VI_BACKEND {
    state MASTER
    interface eth0
    virtual_router_id 62
    priority 100
    advert_int 1
    unicast_src_ip 10.10.20.21
    unicast_peer {
        10.10.20.22
    }
    authentication {
        auth_type PASS
        auth_pass backpass
    }
    virtual_ipaddress {
        10.10.20.150
    }
}
