vrrp_instance VI_FRONTEND {
    state BACKUP
    interface eth0
    virtual_router_id 61
    priority 90
    advert_int 1
    unicast_src_ip 10.10.20.12
    unicast_peer {
        10.10.20.11
    }
    authentication {
        auth_type PASS
        auth_pass frontpass
    }
    virtual_ipaddress {
        10.10.20.100
    }
}
